apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: kube-dns-policy
  namespace: kube-system
spec:
  podSelector:
    matchLabels:
      "k8s-app": "kube-dns"
  ingress:
  - ports:
    - port: 53
      protocol: TCP
    - port: 53
      protocol: UDP
    from:
    - namespaceSelector: {}
